### ISSUE TITLE
Error in select_read_len_cutoff_amber.py due to missing read length in mismatch rate table

### ISSUE THREAD

**Issue by verku** [NBISweden/DNAharvester#63]
Error when running `BAM_PROCESSING:ESTIMATE_READ_LEN_CUTOFF` on samples from the eager test data:

```
Traceback (most recent call last):
    File "/cfs/klemming/home/v/verenaku/Private/LTS-L_Dalen_2302/read-harvester/bin/select_read_len_cutoff_amber.py", line 56, in <module>
      avg_mismatch_rate = mean([mismatch_rates[read_lengths.index(i)] for i in range(40, 61)])
    File "/cfs/klemming/home/v/verenaku/Private/LTS-L_Dalen_2302/read-harvester/bin/select_read_len_cutoff_amber.py", line 56, in <listcomp>
      avg_mismatch_rate = mean([mismatch_rates[read_lengths.index(i)] for i in range(40, 61)])
  ValueError: 40 is not in list
```

Inspecting the input file *.amber_plot.txt, this sample does not have any reads with a mismatch rate under 42 bp

**Comment by bilalbioinfo** [comment]
fixed now a05b464f6b207ff4dae9e11388aacb8006619c5b
